spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rg1472103@gmail.com
    password: yyiuubszymnpmihb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
